networks:
  docker-local_net:
    driver: bridge

volumes:
  db: {}
  survey-files: {}

services:
  caddy:
    container_name: 'qlarr-caddy'
    image: public.ecr.aws/qlarr/frontend:d4aaf542b5eebe10620b2918c34358d43fb7fc16
    environment:
      VITE_PROTOCOL: "http"
      VITE_FRONT_END_HOST: "localhost:3000"
      VITE_BE_URL: "http://localhost:8080"
    depends_on:
      - backend-app
    ports:
      - "3000:3000"
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile:ro
    networks:
      - docker-local_net

  mailhog:
    container_name: 'qlarr-mailhog'
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - docker-local_net

  backend-app:
    container_name: 'qlarr-backend'
    image: public.ecr.aws/qlarr/backend:87959588d5cfd6ab65bd303124519f25ab411d78
    ports:
      - "8080:8080"
    networks:
      - docker-local_net
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - survey-files:/var/qlarr/resources
    environment:
      JWT_SECRET: "bG9jYWwtZGV2LXNlY3JldC1jaGFuZ2UtbWUtbmVlZHMtdG8tYmUtbG9uZy1lbm91Z2g="
      MAIL_HOST: "mailhog"
      MAIL_PORT: "1025"
      MAIL_SMTP_SSL: "false"
      MAIL_SMTP_STARTTLS: "false"
      MAIL_USERNAME: "noreply@qlarr.local"
      MAIL_PASSWORD: ""
      SPRING_PROFILES_ACTIVE: "docker"
      DB_URL: "jdbc:postgresql://postgres-db:5432/qlarr"
      DB_USER: "qlarr"
      FILE_SYSTEM_ROOT_FOLDER: "/var/qlarr/resources"
      DB_PASSWORD: "qlarr"
      FRONTEND_URL: "http://localhost:3000"

  postgres-db:
    container_name: 'postgres-db'
    image: postgres:15.1
    networks:
      - docker-local_net
    environment:
      POSTGRES_USER: "qlarr"
      POSTGRES_PASSWORD: "qlarr"
      POSTGRES_DB: "qlarr"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qlarr"]
      interval: 10s
      timeout: 5s
      retries: 5
