// Single source of truth for question type display labels.
// Used by both QuestionCard (component mapping) and AnalyticsSurvey (header labels).
export const QUESTION_TYPE_LABELS = {
  SCQ: 'Single Choice',
  MCQ: 'Multiple Choice',
  NPS: 'Net Promoter Score',
  RANKING: 'Ranking',
  NUMBER: 'Number',
  DATE: 'Date',
  TIME: 'Time',
  DATE_TIME: 'Date & Time',
  TEXT: 'Short Text',
  PARAGRAPH: 'Long Text',
  EMAIL: 'Email',
  MULTIPLE_TEXT: 'Multiple Text',
  AUTOCOMPLETE: 'Autocomplete',
  ICON_SCQ: 'Icon Single Choice',
  ICON_MCQ: 'Icon Multiple Choice',
  SCQ_ARRAY: 'Single Choice Array',
  MCQ_ARRAY: 'Multiple Choice Array',
  SCQ_ICON_ARRAY: 'Icon Single Choice Array',
  MCQ_ICON_ARRAY: 'Icon Multiple Choice Array',
  IMAGE_RANKING: 'Image Ranking',
  IMAGE_SCQ: 'Image Single Choice',
  IMAGE_MCQ: 'Image Multiple Choice',
  FILE_UPLOAD: 'File Upload',
  SIGNATURE: 'Signature',
  PHOTO_CAPTURE: 'Photo Capture',
  BARCODE: 'Barcode',
};
