name: Release Android
on:
  workflow_dispatch: {}
jobs:
  release-android:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          registry-url: https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run build-android
        env:
          CI: false

      - name: Publish Plugin to GitHub Packages 📦
        run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
